extra-deps:
  - xmonad-0.15
  - xmonad-contrib-0.15
  - X11-xft-0.3.1
resolver: lts-11.8
nix:
  enable: true
  packages: [ zlib
              xorg.libX11
              xorg.libXrandr
              xorg.libXext
              xorg.libXft
              pkgconfig ]
